# Generated by Django 5.1.7 on 2025-03-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_order_user_alter_order_delivery_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
