# Generated by Django 5.1.7 on 2025-03-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
    ]
